### ISSUE TITLE
tambahan fitur

### ISSUE THREAD

**Issue by monchichis** [egodasa/aplikasiujianberbasisweb#9]
mungkin bisa di tambahkan fitur export import ke excel atau pdf gan

**Comment by egodasa** [comment]
@monchichis  Terima kasih atas saran Anda. Fitur eksport hasil ujian sendiri sudah ada. 
Dan sekedar info, program ini adalah program skripsi saya dan sudah disidangkan pada bulan April 2018. Sehingga Saya tidak berpikiran lagi untuk mengembangkannya.
